### ISSUE TITLE
JSON Support?

### ISSUE THREAD

**Issue by aadrian** [xvik/yaml-updater#42]
Hi,

The tool is very useful for merging YML structures (even as library/util to be used by programs).

Is there any chance to make work with JSON too?

Thank you.

**Comment by xvik** [comment]
Hi! 
Definitely no.
The main intention was to preserve comments while updating YAML configuration files.

JSON does not support comments so there is no such problem. 
You can use jackson to merge json files (and then (pretty) write it back, if required).

**Comment by aadrian** [comment]
> JSON does not support comments so there is no such problem.

Some configurations are in JSON, (as not everything is YAML, especially Node and JS parts), so even without comments merging would still be helpful.


> You can use jackson to merge json files (and then (pretty) write it back, if required).

Sure, but the "merge" behaviour would not be 100% compatible with what `yaml-updater` provides.

Since JSON is a subset of YAML, https://yaml.org/spec/1.2.2/ , I was thinking more of a on the fly conversion to YAML, merging as it works now, and depending on the option (e.g. --output=json) converting back, or letting it as YAML output (this would also allow to merge e.g. a JSON with a YAML).

**Comment by xvik** [comment]
> Sure, but the "merge" behaviour would not be 100% compatible with what yaml-updater provides.

Current behaviour is "don't override existing values". In jackson the same behaviour would be if you load sequentially two json files: first file with modifications and then the original file (jackson would preserve all values from the first file that not exists in second one and override existing values).

> Some configurations are in JSON, (as not everything is YAML, especially Node and JS parts, or some REST response), so even without comments merging would still be helpful.

I really doubt anyone have problems with that. JSON is a very simple format and it is well supported (even merge cases).

For YAML, the problem is the absence of no parser correctly preserving comments and formatting, so it is impossible
to read and write yaml file without chages (becuase it is almost impossible to correctly associate comments with nodes in yaml tree). 
Only becuase of this I have to write custom YAML parser which would be able to preserve file structure (and comments). This is not a strict parser with many assumptions, supposed to solve only one task - preserve original file format and be able to modify file (know its structure). The parser didn't even have errors handling - it use snakeyaml parser for validations.

For JSON you don't need such complications: any merge scenario could be written in a few lines of code ([literally](https://www.logicbig.com/tutorials/misc/jackson/reader-for-updating.html)).

Technically it's possible to adopt project to work with JSON, but I don't see any reason for this: jackson could aready do it, why using somehting else (possibly buggy).
